# Generated by Django 2.2.3 on 2019-07-14 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190714_1854'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
